CREATE TABLE `SYS_MANAGER` (
	`ID` INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
	`USER_NAME` VARCHAR(20) NOT NULL COMMENT '用户名',
  `PASSWORD` VARCHAR(64) NOT NULL COMMENT '用户密码',
  `REMEMBER_TOKEN` VARCHAR(255) NULL COMMENT '记住密码',
  `NICK_NAME` VARCHAR(100) NULL COMMENT '用户昵称',
  `AVATAR` VARCHAR(255) NULL COMMENT '用户头像',
  `TELEPHONE` VARCHAR(11) NULL COMMENT '用户手机号',
  `EMAIL` VARCHAR(255) NULL COMMENT '用户邮箱',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '用户状态：0：禁用，1：启用',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '用户信息表'

CREATE TABLE `SYS_ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `NAME` VARCHAR(30) NOT NULL COMMENT '角色名称',
  `DESCRIBE` VARCHAR(100) NOT NULL COMMENT '角色描述',
  `ICON` VARCHAR(255) NULL COMMENT '角色ICON',
  `SORT` SMALLINT(6) NOT NULL DEFAULT '0' COMMENT '角色排序',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '角色状态：0：禁用，1：启用',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SYS_ROLE_NAME_UNIQUE_INDEX` (`NAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '角色表'

CREATE TABLE `SYS_MANAGER_ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `MANAGER_ID` INT NOT NULL COMMENT '用户ID',
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
	KEY `SYS_MANAGER_ID_INDEX` (`MANAGER_ID`) USING BTREE,
	KEY `SYS_ROLE_ID_INDEX` (`ROLE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '用户与角色关联表'

CREATE TABLE `SYS_MANAGER_GROUP` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '用户组ID',
  `NAME` VARCHAR(30) NOT NULL COMMENT '用户组名',
  `DESCRIBE` VARCHAR(100) NOT NULL COMMENT '用户组描述',
  `ICON` VARCHAR(255) NULL COMMENT '用户组ICON',
  `ENABLED` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '用户组状态：0：禁用，1：启用',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SYS_MANAGER_GROUP_NAME_UNIQUE_INDEX` (`NAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '用户组表'

CREATE TABLE `SYS_MANAGER_GROUP_MANAGER` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `MANAGER_GROUP_ID` INT NOT NULL COMMENT '用户组ID',
  `MANAGER_ID` INT NOT NULL COMMENT '用户ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `SYS_MANAGER_GROUP_ID_INDEX` (`MANAGER_GROUP_ID`) USING BTREE,
	KEY `SYS_MANAGER__ID_INDEX` (`MANAGER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '用户组与用户信息关联表'

CREATE TABLE `SYS_MANAGER_GROUP_ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `MANAGER_GROUP_ID` INT NOT NULL COMMENT '用户组ID',
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY `SYS_MANAGER_GROUP_ID_INDEX` (`MANAGER_GROUP_ID`) USING BTREE,
  KEY `SYS_ROLE_ID_INDEX` (`ROLE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '用户组与角色关联表'



-- ----------------------------
--  Table structure for `SYS_MENU`
-- ----------------------------
CREATE TABLE `SYS_MENU` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '菜单ID',
  `PERENT_ID` INT NULL COMMENT '菜单父级ID',
  `NAME` VARCHAR(30) NOT NULL COMMENT '菜单名称',
  `URL` VARCHAR(255) NULL COMMENT '菜单URL',
  `ICON` VARCHAR(255) NULL COMMENT '菜单ICON',
  `SORT` INT NOT NULL DEFAULT '0' COMMENT '菜单排序',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SYS_MENU_NAME_UNIQUE_INDEX` (`NAME`) USING BTREE,
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '菜单表'

-- ----------------------------
--  Table structure for `SYS_PAGE_ELEMENT`
-- ----------------------------
CREATE TABLE `SYS_PAGE_ELEMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '页面元素ID',
  `PAGE_ELEMENT_NAME` VARCHAR(100) NOT NULL COMMENT '页面元素名称',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '页面元素表'

-- ----------------------------
--  Table structure for `SYS_FILE`
-- ----------------------------
CREATE TABLE `SYS_FILE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '文件编号',
  `FILE_NAME` VARCHAR(50) NOT NULL COMMENT '文件名称',
  `FILE_PATH` VARCHAR(255) NULL COMMENT '文件路径',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '文件表'

-- ----------------------------
--  Table structure for `SYS_PERMISSION`
-- ----------------------------
CREATE TABLE `SYS_PERMISSION` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '权限编号',
  `PERMISSION_TYPE` VARCHAR(50) NOT NULL COMMENT '权限类型',
  `HTTP_METHOD`,
  `HTTP_PATH`,
  `SORT`,
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '权限表'

-- ----------------------------
--  Table structure for `SYS_PERMISSION_MENU`
-- ----------------------------
CREATE TABLE `SYS_PERMISSION_MENU` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `PERMISSION_ID` INT NOT NULL COMMENT '权限ID',
  `MENU_ID` INT NOT NULL COMMENT '菜单ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY(`Permission_ID`) USING BTREE,
  KEY(`MENU_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '权限与菜单关联表'

-- ----------------------------
--  Table structure for `SYS_PERMISSION_PAGE`
-- ----------------------------
CREATE TABLE `SYS_PERMISSION_PAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '编号',
  `Permission_ID` INT NOT NULL COMMENT '权限ID',
  `PAGE_ID` INT NOT NULL COMMENT '页面元素ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY(`Permission_ID`) USING BTREE,
  KEY(`PAGE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '权限与页面元素关联表'

-- ----------------------------
--  Table structure for `SYS_PERMISSION_FILE`
-- ----------------------------
CREATE TABLE `SYS_PERMISSION_FILE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `Permission_ID` INT NOT NULL COMMENT '权限ID',
  `FILE_ID` INT NOT NULL COMMENT '文件ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY(`Permission_ID`) USING BTREE,
  KEY(`FILE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '权限与文件关联表'

-- ----------------------------
--  Table structure for `SYS_OPERATION`
-- ----------------------------
CREATE TABLE `SYS_OPERATION` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `PARENT_ID` INT NOT NULL DEFAULT '0' COMMENT '父级ID',
  `OPERATION_NAME` VARCHAR(50) NOT NULL COMMENT '操作名称',
  `OPERATION_CODE` VARCHAR(50) NULL COMMENT '操作编码',
  `L_JURLQZ` VARCHAR(100) NULL COMMENT '拦截URL前缀',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '功能操作表'

-- ----------------------------
--  Table structure for `SYS_PERMISSION_OPERATION`
-- ----------------------------
CREATE TABLE `SYS_PERMISSION_OPERATION` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `Permission_ID` INT NOT NULL COMMENT '权限ID',
  `OPERATION_ID` INT NOT NULL COMMENT '操作ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY(`Permission_ID`) USING BTREE,
  KEY(`OPERATION_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '权限与功能操作关联表'

-- ----------------------------
--  Table structure for `SYS_ROLE_Permission`
-- ----------------------------
CREATE TABLE `SYS_ROLE_PERMISSION` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `Permission_ID` INT NOT NULL COMMENT '权限ID',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
  KEY(`ROLE_ID`) USING BTREE,
  KEY(`Permission_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '角色与权限关联表'

-- ----------------------------
--  Table structure for `SYS_OPERATION_LOG`
-- ----------------------------
CREATE TABLE `SYS_OPERATION_LOG` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  -- `TYPE_ID` INT NOT NULL COMMENT '日志类型',
  `USER_ID` INT NOT NULL COMMENT '用户ID',
  `METHOD` VARCHAR(50) NOT NULL COMMENT '请求方式',
  `IP` VARCHAR(50) NOT NULL COMMENT '日志IP地址',
  `PATH` VARCHAR(100) NOT NULL COMMENT '请求路径',
  `CONTENT` VARCHAR(255) NULL COMMENT '日志内容',
  `CREATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '日志表'
